### PR TITLE
Add Support For Lazy Loading Poster Attributes on <video> Tags

### LINKED ISSUE #279: Adding Support for Video Tag Posters
We are currently using the plugin for lazy loading images and its working great.  On the same page we also have a number of video elements, some of which are off screen at load time.  We thought it would be a nice feature to be able to lazy load the posters images for the videos the same way the other images are loaded.  We have this working and I will submit a pull request shortly.  Please let us know what you think about this feature.

### PR DESCRIPTION
**Pull request by leemicw**
This pull request resolves #279

### CODE REVIEW

**Comment by leemicw** [comment]
@tuupola do you have any feedback on why this wasn't an appropriate addition?

**Comment by tuupola** [comment]
It seems this was closed when I deleted an old branch. I think I am still able to cherry-pick this to `master`.

**Comment by leemicw** [comment]
awesome, thank you.  if its any help I can reapply these changes to a current copy of master and submit a new PR

**Comment by tuupola** [comment]
That would be great. Thanks!

**Pull request closed without merging**
